"""empty message

Revision ID: 0ea59f0ba6b6
Revises: aea175c19bcf
Create Date: 2017-10-01 11:05:06.383826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ea59f0ba6b6'
down_revision = 'aea175c19bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('event', sa.String(length=80), nullable=True))
    op.drop_column('schedule', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('title', mysql.VARCHAR(length=80), nullable=True))
    op.drop_column('schedule', 'event')
    # ### end Alembic commands ###
