"""empty message

Revision ID: aea175c19bcf
Revises: e931cf78e93b
Create Date: 2017-10-01 10:14:06.074800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aea175c19bcf'
down_revision = 'e931cf78e93b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presenters', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('schedule', sa.Column('city', sa.String(length=30), nullable=True))
    op.add_column('schedule', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('schedule', sa.Column('state', sa.String(length=2), nullable=True))
    op.add_column('schedule', sa.Column('status', sa.String(length=20), nullable=True))
    op.drop_column('schedule', 'mtg_topic5')
    op.drop_column('schedule', 'mtg_time5')
    op.drop_column('schedule', 'mtg_topic3')
    op.drop_column('schedule', 'mtg_time4')
    op.drop_column('schedule', 'mtg_topic4')
    op.drop_column('schedule', 'mtg_time3')
    op.drop_column('schedule', 'mtg_time2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('mtg_time2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('schedule', sa.Column('mtg_time3', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('schedule', sa.Column('mtg_topic4', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('schedule', sa.Column('mtg_time4', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('schedule', sa.Column('mtg_topic3', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('schedule', sa.Column('mtg_time5', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('schedule', sa.Column('mtg_topic5', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('schedule', 'status')
    op.drop_column('schedule', 'state')
    op.drop_column('schedule', 'date')
    op.drop_column('schedule', 'city')
    op.drop_column('presenters', 'active')
    # ### end Alembic commands ###
