"""empty message

Revision ID: e931cf78e93b
Revises: a6a4005a1977
Create Date: 2017-09-30 15:52:39.923433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e931cf78e93b'
down_revision = 'a6a4005a1977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('presenter', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'schedule', 'presenters', ['presenter'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.drop_column('schedule', 'presenter')
    # ### end Alembic commands ###
